### ISSUE TITLE
web运行不起来

### ISSUE THREAD

**Issue by Zhangxuri** [easy-mock/easy-mock-docker#14]
Linux VM_0_9_centos 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

1.文件目录结构
```
.
├── data
│   ├── db
│   └── redis
├── docker-compose.yml
├── logs
└── production.json
```
2.docker-compose.xml
```
version: "3.3"
services:
  mongodb:
    image: mongo:3.4
    volumes:
      - type: bind
        source: ./data/db # 数据库文件存放地址，根据需要修改为本地地址
        target: /data/db
  redis:
    image: redis:4.0.6
    command: redis-server --appendonly yes
    volumes:
      - type: bind
        source: ./data/redis # redis 数据文件存放地址，根据需要修改为本地地址
        target: /data
  web:
    image: easymock/easymock:1.6.0
    command: /bin/bash -c "npm start"
    links:
      - mongodb:mongodb
      - redis:redis
    ports:
      - 7300:7300
    volumes:
      - type: bind 
        source: ./logs # 日志地址，根据需要修改为本地地址
        target: /home/easy-mock/easy-mock/logs
      - type: bind
        source: ./production.json # 配置地址，请使用本地配置地址替换
        target: /home/easy-mock/easy-mock/config/production.json
```
3.production.json
```
{
  "port": 7300,
  "host": "0.0.0.0",
  "pageSize": 30,
  "proxy": false,
  "unsplashClientId": "",
  "blackList": {
    "projects": [],
    "ips": []
  },
  "rateLimit": {
    "max": 1000,
    "duration": 1000
  },
  "jwt": {
    "expire": "14 days",
    "secret": "shared-secret"
  },
  "upload": {
    "types": [".jpg", ".jpeg", ".png", ".gif", ".json", ".yml", ".yaml"],
    "size": 5242880,
    "dir": "../public/upload",
    "expire": {
      "types": [".json", ".yml", ".yaml"],
      "day": -1
    }
  },
  "ldap": {
    "server": "",
    "bindDN": "",
    "password": "",
    "filter": {
      "base": "",
      "attributeName": ""
    }
  },
  "fe": {
    "copyright": "",
    "storageNamespace": "easy-mock_",
    "timeout": 25000,
    "publicPath": "/dist/"
  }
}
```
4. run `docker-compose up -d`
5. 
```
7afb04f5f7c0        easymock/easymock:1.6.0   "/bin/bash -c 'npm s…"   8 seconds ago       Exited (1) 3 seconds ago                                    easymock_web_1
```
6. run `docker logs 7afb04f5f7c0`
```
> easy-mock@1.6.0 start /home/easy-mock/easy-mock
> cross-env NODE_ENV=production node app

server started at http://0.0.0.0:7300
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: EACCES: permission denied, open 'logs/2019-01-07-info.log'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! easy-mock@1.6.0 start: `cross-env NODE_ENV=production node app`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the easy-mock@1.6.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/easy-mock/.npm/_logs/2019-01-07T03_52_48_130Z-debug.log
```
