### ISSUE TITLE
npm start 时的权限问题

### ISSUE THREAD

**Issue by luffy1937** [easy-mock/easy-mock-docker#5]
主机上的docker一般是root权限来操作的，如果bind的volumes不存在，会已以root权限创建。所以如果以easy-mock用户执行“npm start”命令，会有文件权限问题，如下：

 #![default](https://user-images.githubusercontent.com/15139854/38907904-84ad21e4-42f0-11e8-9fba-a6db3be3f333.png)
#4

**Comment by DuanPengfei** [comment]
ok，这个问题实际中应该是由于 docker-compose.yml 中路径配置有误导致的，如果确实不需要 volume 应该删除 volumes 下的各个配置。

若做兼容，需要在容器内将目录权限修改正确，但是感觉不做兼容更好些，有错误及时抛出来，如果确实不需要把容器内日志等信息保留下来，删除 docker-compose.yml volumes 配置项即可。如下所示：

```
version: "3.3"
services:
  mongodb:
    image: mongo:3.4
  redis:
    image: redis:4.0.6
    command: redis-server --appendonly yes
  web:
    image: easymock/easymock:1.5.1
    command: /bin/bash -c "npm start"
    links:
      - mongodb:mongodb
    ports:
      - 7300:7300
    volumes:
      - type: bind
        source: ./production.json # 配置地址，请使用本地配置地址替换
        target: /home/easy-mock/easy-mock/config/production.json
```

production.json 应该还是需要保留的，否则内部启动配置无法按照用户自己的想法定制了。
