### ISSUE TITLE
win10下部署报错:Operation not permitted, terminating

### ISSUE THREAD

**Issue by gaoshijun1993** [easy-mock/easy-mock-docker#7]
```
2018-06-01T09:01:02.494+0000 I -        [initandlisten] Assertion: 28595:1: Operation not permitted src/mongo/db/storage/wiredtiger/wiredtiger_kv_engine.cpp 277

easy-mock-docker_mongodb_1 exited with code 100
```

**Comment by DuanPengfei** [comment]
提供下系统版本，Docker 版本，easy-mock 镜像版本，我们看看是否可以复现。

**Comment by gaoshijun1993** [comment]
@DuanPengfei 使用的Windows 版本 Docker,貌似是因为Mongodb 不支持直接映射,只能使用具名volume

> The default Docker setup on Windows and OS X uses a VirtualBox VM to host the Docker daemon. Unfortunately, the mechanism VirtualBox uses to share folders between the host system and the Docker container is not compatible with the memory mapped files used by MongoDB (see vbox bug, docs.mongodb.org and related jira.mongodb.org bug). This means that it is not possible to run a MongoDB container with the data directory mapped to the host.

**Comment by CoinXu** [comment]
windows下只能使用volume，不能直接bind磁盘。
1. 创建volume
```bash
docker volume create mongodata
docker volume create redisdata
docker volume create logsdata
```
2. 将`docker-compose.yml`修改如下
```yml
version: "3.3"
services:
  mongodb:
    image: mongo:3.4
    volumes:
      - type: volume
        source: mongodata
        target: /data/db
  redis:
    image: redis:4.0.6
    command: redis-server --appendonly yes
    volumes:
      - type: volume
        source: redisdata
        target: /data
  web:
    image: easymock/easymock:1.5.1
    command: /bin/bash -c "npm start"
    links:
      - mongodb:mongodb
    ports:
      - 7300:7300
    volumes:
      - type: volume
        source: logsdata # 日志地址，根据需要修改为本地地址
        target: /home/easy-mock/easy-mock/logs
      - type: bind
        source: ./production.json # 配置地址，请使用本地配置地址替换
        target: /home/easy-mock/easy-mock/config/production.json

# 一定要声明volumes
volumes:
  mongodata:
    external:
      name: mongodata
  redisdata:
    external:
      name: redisdata
  logsdata:
    external:
      name: logsdata
```
3. 删除`production.js`中的`db`配置
4. 运行`docker-compose up -d`
